name: code analysis & formatting

on: [push, pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v2.8.0
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./flutter_secure_storage
      - name: Linter - Android & iOS
        run: flutter analyze
        working-directory: ./flutter_secure_storage
      - name: Linter - Platform Interface
        run: flutter analyze
        working-directory: ./flutter_secure_storage_platform_interface
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v2.8.0
      - name: Format - Android & iOS
        run: flutter format -n --set-exit-if-changed .
        working-directory: ./flutter_secure_storage
      - name: Format - Platform Interface
        run: flutter format -n --set-exit-if-changed .
        working-directory: ./flutter_secure_storage_platform_interface
